---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-du
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "xeth",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.160.0/24",
        "gateway": "192.168.160.254",
        "rangeStart": "192.168.160.1",
        "rangeEnd": "192.168.160.1"
      }
    }

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-du-ens
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "ens18f1",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.12.0/24",
        "rangeStart": "192.168.12.105",
        "rangeEnd": "192.168.12.106"
      }
    }
