name: CI FPGA

on:
  push:
    branches:
      - 'main'
    paths:
      - 'fpga/**'

jobs:
  centos7:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fpga
          platforms: linux/amd64
          push: true
          tags: |
            quay.io/baicell/fpga-driver:v${{ steps.date.outputs.date }}

